# Generated by Django 2.2 on 2020-09-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20200908_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='notice',
            field=models.CharField(max_length=300, verbose_name='课程公告'),
        ),
    ]
