# Generated by Django 2.2 on 2020-09-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_remove_course_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='notice',
            field=models.IntegerField(default=0, max_length=300, verbose_name='课程公告'),
        ),
    ]
